services:
  - type: web
    name: django-sensors
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py populate_data --count 10
      python manage.py collectstatic --noinput
  startCommand: gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: awd-data-6.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: sensors-postgres
          property: connectionString
      - key: PYTHONPATH
        value: /opt/render/project/src

databases:
  - name: sensors-postgres
    plan: free
