# Generated by Django 5.2.6 on 2025-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensordata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deviceid', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('phvalue', models.FloatField()),
                ('tds', models.FloatField()),
                ('o2', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
