# Generated by Django 5.2.6 on 2025-09-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensordata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('phvalue', models.FloatField()),
                ('tds', models.FloatField()),
            ],
        ),
    ]
