# Generated by Django 5.2.6 on 2025-09-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='deviceid',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
