# Generated by Django 5.2.6 on 2025-09-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_sensordata_deviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='o2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
